# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proton < Formula
  desc "cli protobuf to json converter"
  homepage "https://github.com/beatlabs/proton"
  version "2.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beatlabs/proton/releases/download/v2.0.2/proton_Darwin_x86_64.tar.gz"
      sha256 "52ea01f462168327669fdb0b10f59953086c2ab1762bd872913adc8c2af54e6c"

      def install
        bin.install "proton"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beatlabs/proton/releases/download/v2.0.2/proton_Linux_x86_64.tar.gz"
      sha256 "9644df017d70fa0e40755abc9b43e2dd56c0fa7611a142e7b3a1f8ffee9772b2"

      def install
        bin.install "proton"
      end
    end
  end

  test do
    system "#{bin/proton}"
  end
end
